# Generated by Django 4.2.4 on 2023-08-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gadget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gadget_name", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("checked_out_time", models.DateTimeField()),
                ("returned_time", models.DateTimeField()),
                ("condition", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Asset.gadgetuser",
                    ),
                ),
            ],
        ),
    ]
